### ISSUE TITLE
Выбор предобученной модели

### ISSUE THREAD

**Issue by baicorporation** [baicorporation/ASP#1]
Сравнить предложенные архитектуры по значениям метрик BLEU, ROUGE, BERTScore и выявить модель с наилучшими значениями

**Comment by nikiduki** [comment]
Ноутбук по сравнению моделей: [Составление таблицы сравнения моделей](https://colab.research.google.com/drive/1G30lHSC2lt8HUlxCQb4AUIstC4c6rj20?usp=sharing)
![Сравнительная таблица](https://github.com/baicorporation/ASP/assets/72929274/092253ed-5788-481a-b693-5733d0394983)
